/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vigilante;

/**
 *
 * @author alejo
 */
public class Panel_RegistrarSalida extends javax.swing.JPanel {

    /**
     * Creates new form Panel_RegistrarSalida
     */
    public Panel_RegistrarSalida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        contenedor_registrarSalida = new javax.swing.JPanel();
        etq_titulo = new javax.swing.JLabel();
        btn_buscarPc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_computador = new javax.swing.JTable();
        btn_registrarSalida = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        campo_id = new javax.swing.JTextField();
        userLabel7 = new javax.swing.JLabel();

        contenedor_registrarSalida.setBackground(new java.awt.Color(0, 74, 173));

        etq_titulo.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        etq_titulo.setForeground(new java.awt.Color(255, 255, 255));
        etq_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etq_titulo.setText("Registrar Salida");

        btn_buscarPc.setBackground(new java.awt.Color(102, 0, 0));
        btn_buscarPc.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btn_buscarPc.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscarPc.setText("Buscar pc");
        btn_buscarPc.setToolTipText("");
        btn_buscarPc.setBorder(null);
        btn_buscarPc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tabla_computador.setBackground(new java.awt.Color(56, 128, 255));
        tabla_computador.setForeground(new java.awt.Color(255, 255, 255));
        tabla_computador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código_equipo", "Marca", "Persona", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_computador);

        btn_registrarSalida.setBackground(new java.awt.Color(102, 0, 0));
        btn_registrarSalida.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btn_registrarSalida.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarSalida.setText("Registrar Salida");
        btn_registrarSalida.setBorder(null);
        btn_registrarSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        campo_id.setBackground(new java.awt.Color(0, 74, 173));
        campo_id.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campo_id.setForeground(new java.awt.Color(204, 204, 255));
        campo_id.setText("Ingrese Cédula");
        campo_id.setBorder(null);
        campo_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo_idMousePressed(evt);
            }
        });

        userLabel7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        userLabel7.setForeground(new java.awt.Color(255, 255, 255));
        userLabel7.setText("Cédula de usuario");

        javax.swing.GroupLayout contenedor_registrarSalidaLayout = new javax.swing.GroupLayout(contenedor_registrarSalida);
        contenedor_registrarSalida.setLayout(contenedor_registrarSalidaLayout);
        contenedor_registrarSalidaLayout.setHorizontalGroup(
            contenedor_registrarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_registrarSalidaLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(contenedor_registrarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedor_registrarSalidaLayout.createSequentialGroup()
                        .addComponent(etq_titulo)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedor_registrarSalidaLayout.createSequentialGroup()
                        .addGroup(contenedor_registrarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userLabel7)
                            .addComponent(campo_id)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscarPc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedor_registrarSalidaLayout.createSequentialGroup()
                        .addComponent(btn_registrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedor_registrarSalidaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        contenedor_registrarSalidaLayout.setVerticalGroup(
            contenedor_registrarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor_registrarSalidaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(etq_titulo)
                .addGap(40, 40, 40)
                .addComponent(userLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedor_registrarSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarPc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_registrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor_registrarSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor_registrarSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campo_idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_idMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_idMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarPc;
    private javax.swing.JButton btn_registrarSalida;
    private javax.swing.JTextField campo_id;
    private javax.swing.JPanel contenedor_registrarSalida;
    private javax.swing.JLabel etq_titulo;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable tabla_computador;
    private javax.swing.JLabel userLabel7;
    // End of variables declaration//GEN-END:variables
}
